(function(g){var window=this;'use strict';var UXa=function(a,b){var c=[];return g.et(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},q4=function(a,b){return"getAll"in IDBIndex.prototype?g.Ts(a.j.getAll(b,void 0)):UXa(a,b)},VXa=function(a,b){return g.Zs(a,["captions"],{mode:"readonly",
Kc:!0},function(c){return g.Ana(c.objectStore("captions"),b,void 0)})},WXa=function(a){var b=new g.Dx("und",new g.cA("Default","und",!0));
b.captionTracks=a.captionTracks;return b},XXa=function(a){return new g.pi(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},k=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.Vba(m,g.Ua(f,l),k);
else b(e)})},r4=function(a){this.j=a},s4=function(){r4.apply(this,arguments)},t4=function(){s4.apply(this,arguments)},u4=function(){s4.apply(this,arguments)},v4=function(){s4.apply(this,arguments)},w4=function(){r4.apply(this,arguments)},x4=function(){s4.apply(this,arguments)},y4=function(){s4.apply(this,arguments)},z4=function(){s4.apply(this,arguments)},A4=function(){s4.apply(this,arguments)},B4=function(){s4.apply(this,arguments)},C4=function(){s4.apply(this,arguments)},D4=function(){s4.apply(this,
arguments)},E4=function(){s4.apply(this,arguments)},F4=function(){s4.apply(this,arguments)},G4=function(){s4.apply(this,arguments)},H4=function(){s4.apply(this,arguments)},I4=function(){r4.apply(this,arguments)},J4=function(){s4.apply(this,arguments)},K4=function(){s4.apply(this,arguments)},L4=function(){s4.apply(this,arguments)},M4=function(){s4.apply(this,arguments)},N4=function(){s4.apply(this,arguments)},O4=function(){s4.apply(this,arguments)},P4=function(){s4.apply(this,arguments)},Q4=function(){s4.apply(this,
arguments)},R4=function(){s4.apply(this,arguments)},S4=function(){s4.apply(this,arguments)},T4=function(){s4.apply(this,arguments)},U4=function(){s4.apply(this,arguments)},V4=function(){s4.apply(this,arguments)},W4=function(){s4.apply(this,arguments)},YXa=function(a){var b=g.xD();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.Mva(b);JSON.stringify(b);return b},ZXa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.pt(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.AD(b),3):d.return();c=d.u;return d.return(g.Zs(c,["index","media","captions"],{mode:"readwrite",Kc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Rs.all(e).then(function(){})}))})},$Xa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.pt(),2);if(3!=c.j){a=c.u;if(!a)throw g.Ps("rvdfd");return g.A(c,g.AD(a),3)}b=c.u;return c.return(g.Zs(b,["index","media"],{mode:"readwrite",Kc:!0},function(d){var e={};return g.ct(d.objectStore("index"),{},function(f){var k=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.Rs.resolve(void 0);if(k){var m=k[1];k=k[2];e[m]=e[m]||{};var n;e[m][k]=g.Sva(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.Rs.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},k=g.r(Object.keys(e)),l=k.next();!l.done;l=k.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=YXa(f);return g.Dna(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.Wva);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},aYa=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.pt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Ps("wct");return g.A(e,g.AD(c),3)}d=e.u;return g.A(e,g.Zs(d,["captions"],{mode:"readwrite",Kc:!0},function(f){var k=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.$s(f,b[l],a+"|"+b[l].metadata.vss_id);k.push(m)}return g.Rs.all(k)}),0)})},bYa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.pt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Ps("gactfv");return g.A(e,g.AD(c),3)}d=e.u;return e.return(VXa(d,b))})},cYa=function(a){return g.B(function(b){g.zD(a,0);
return b.return(ZXa(a))})},dYa=function(a){return{context:g.NH(),
videoIds:a}},X4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},Y4=function(a,b){b=void 0===b?{}:b;
g.Fs.call(this,g.RTa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,Y4.prototype)},eYa=function(a){return new Y4("WRONG_DATA_TYPE",{mU:a})},fYa=function(a){return a instanceof Error?new Y4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new Y4("UNKNOWN_ENCODE_ERROR")},gYa=function(a){return a instanceof Error?new Y4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new Y4("UNKNOWN_DECODE_ERROR")},hYa=function(a,b){a=a instanceof
Y4?a:b(a);
g.S(a);throw a;},iYa=function(){},jYa=function(a,b,c){try{return a.B(b,c)}catch(d){hYa(d,fYa)}},kYa=function(a,b,c){try{return a.u(b,c)}catch(d){hYa(d,gYa)}},Z4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},$4=function(a){this.j=a},a5=function(){},lYa=function(){this.j={};
this.j[0]=new a5;if(!g.Q("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.Gs();var c=Z4(b);var d=new $4(new g.TB(c),new g.SB(c))}catch(e){throw a=e instanceof Error?new Y4("KEY_CREATION_FAILED",{originalMessage:e.message}):new Y4("KEY_CREATION_FAILED"),g.S(a),a;}a[1]=d}},b5=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new Y4("INVALID_ENCODER_VERSION",{mU:b}),g.S(b),b;return a},nYa=function(a){var b=mYa[a];
if(b)return b;g.Ov(new g.Fs("Entity model not found.",{entityType:a}))},oYa=function(a){var b=new lYa,c=a.objectStore("EntityStore"),d=a.objectStore("EntityAssociationStore");
g.ct(c,{},function(e){var f=e.getValue(),k=kYa(b5(b,f.version),f.data,f.key),l=g.LK(f.key).entityType;l=nYa(l);if(!l)return e.continue();l=(new l(k)).fd();k=[];l=g.r(l);for(var m=l.next();!m.done;m=l.next())k.push(g.$s(d,{parentEntityKey:f.key,childEntityKey:m.value}));return g.Rs.all(k).then(function(){return e.continue()})})},pYa=function(){if(c5)return c5();
var a={};c5=g.Et("PersistentEntityStoreDb",{Nq:(a.EntityStore={Gn:1},a.EntityAssociationStore={Gn:2},a),py:!1,upgrade:function(b,c,d){c(1)&&g.bt(g.Xs(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.Xs(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.bt(b,"byParentEntityKey","parentEntityKey"),g.bt(b,"byChildEntityKey","childEntityKey"));c(3)&&!c(1)&&oYa(d)},
version:g.Q("pes_migrate_association_data")?3:2});return c5()},qYa=function(a){return g.ht(pYa(),a)},rYa=function(a,b){this.j=a;
this.u=b;this.B={}},sYa=function(a,b){return kYa(b5(a.u,b.version),b.data,b.key)},d5=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return sYa(a,d)}})},e5=function(a,b,c){return c?(c=c.map(function(d){return d5(a,d,b)}),g.Rs.all(c)):q4(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return sYa(a,e)})})},g5=function(a,b,c){var d=X4(b),e=b5(a.u,1),f={key:d,
entityType:c,data:jYa(e,b,d),version:1};return a.j.objectStore("EntityStore").get(d).then(function(k){if(k&&k.entityType!==c)throw Error("Incorrect entity type");}).then(function(){return g.Rs.all([g.$s(a.j.objectStore("EntityStore"),f),
tYa(a,b,c)])}).then(function(){f5(a,d,c);
return d})},h5=function(a,b,c){b=b.map(function(d){return g5(a,d,c)});
return g.Rs.all(b)},i5=function(a,b,c){if(null==c?0:c.oL){var d=new Set;
return uYa(a,b,d).then(function(){for(var f=[],k=g.r(d),l=k.next();!l.done;l=k.next())f.push(i5(a,l.value));return g.Rs.all(f).then(function(){})})}var e=g.LK(b).entityType;
return g.Rs.all([a.j.objectStore("EntityStore").delete(b),j5(a,b)]).then(function(){f5(a,b,e)})},vYa=function(a,b){return g.et(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Rs.all([c.delete(),
j5(a,c.uA())]).then(function(){f5(a,c.uA(),b);return c.continue()})})},wYa=function(a,b,c,d){var e=b5(a.u,1);
return d5(a,b,d).then(function(f){if(f){f=g.wK(f,c,void 0);var k={key:b,entityType:d,data:jYa(e,f,b),version:1};return g.Rs.all([g.$s(a.j.objectStore("EntityStore"),k),tYa(a,f,d)])}}).then(function(){f5(a,b,d);
return b})},f5=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},xYa=function(a,b,c){var d=X4(b);
c=nYa(c);if(!c)return g.Rs.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.fd());for(var e=c.next();!e.done;e=c.next())b.push(g.$s(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Rs.all(b).then(function(f){return f.map(function(k){return k[1]})})},j5=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},tYa=function(a,b,c){var d=X4(b);
return j5(a,d).then(function(){return xYa(a,b,c)})},uYa=function(a,b,c){if(c.has(b))return g.Rs.resolve(void 0);
c.add(b);return yYa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Rs.resolve(void 0),f={};
d=g.r(d);for(var k=d.next();!k.done;f={IC:f.IC},k=d.next())f.IC=k.value,e=e.then(function(l){return function(){return uYa(a,l.IC,c)}}(f));
return e}).then(function(){})},yYa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return q4(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(q4(c.index("byChildEntityKey"),f.childEntityKey));return g.Rs.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},k5=function(a,b){g.G.call(this);
this.token=a;this.u=b;this.j=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.Gs());a.onmessage=this.B.bind(this);this.channel=a},l5=function(a,b,c){var d,e,f,k;
return g.B(function(l){if(1==l.j)return g.A(l,qYa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.Zs(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new rYa(m,a.u);return c(e)}),3);
f=l.u;e&&(k=e.B,0<Object.keys(k).length&&(a.channel.postMessage(k),zYa(a,k)));return l.return(f)})},m5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},n5=function(a,b,c){return l5(a,{mode:"readwrite",
Kc:!0},function(d){return g5(d,b,c)})},AYa=function(a,b){return l5(a,{mode:"readwrite",
Kc:!0},function(c){return h5(c,b,"offlineOrchestrationActionWrapperEntity")})},BYa=function(a,b){return l5(a,{mode:"readwrite",
Kc:!0},function(c){return i5(c,b,void 0)})},o5=function(a,b,c){return l5(a,{mode:"readonly",
Kc:!0},function(d){return d5(d,b,c)})},p5=function(a,b,c){return l5(a,{mode:"readonly",
Kc:!0},function(d){return e5(d,b,c)})},zYa=function(a,b){a=g.r(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},CYa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.va(d,2),g.A(d,g.pt(),4);if(2!=d.j){a=d.u;if(!a||!g.Hs()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new lYa;return d.return(new k5(a,b))}c=g.xa(d);c instanceof Error&&g.S(c);return d.return()})},r5=function(){q5||(q5=CYa());
return q5},DYa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},EYa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,r5(),2):(b=c.u)?g.A(c,l5(b,"readwrite",function(d){for(var e={},f={},k=g.r(a),l=k.next();!l.done;f={zg:f.zg,Pr:f.Pr},l=k.next())f.zg=l.value,f.zg.entityKey&&DYa(f.zg)&&(f.Pr=g.Uf(f.zg.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.zg.type&&(l=function(m){return function(){return g5(d,m.zg.payload[m.Pr],m.Pr)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.zg.type&&(l=function(m){return function(){return i5(d,m.zg.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.zg.type&&(l=function(m){return function(){return wYa(d,m.zg.entityKey,m.zg.payload[m.Pr],m.Pr)}}(f)),l&&(e[f.zg.entityKey]=e[f.zg.entityKey]?e[f.zg.entityKey].then(l):l()));
return g.Rs.all(Object.values(e))}),0):c.return()})},FYa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.A0){var d=b,e={type:"ENTITY_LOADED"};void 0!==d&&(e.payload=d);g.A0.dispatch(e)}return g.A(c,EYa(b),2)}b.length=0;g.ua(c)})},GYa=function(a){return void 0!==a},s5=function(a,b){var c=b.ji;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.As("offlineTransferStatusChanged",a)},HYa=function(a){s5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},IYa=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
t5=function(){},u5=function(){},v5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.Gs("CacheStorage get")},JYa=function(){return g.B(function(a){if(void 0!==w5)return a.return(w5);
w5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.va(d,2),g.A(d,x5.open("test-only"),4);case 4:return g.A(d,x5.delete("test-only"),5);case 5:g.wa(d,3);break;case 2:if(c=g.xa(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.ua(d)}})});
return a.return(w5)})},z5=function(){return g.B(function(a){if(1==a.j)return g.A(a,JYa(),2);
if(!a.u)return a.return(void 0);y5||(y5=new u5);return a.return(y5)})},KYa=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,z5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},LYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,z5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},MYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,z5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},A5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},B5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},C5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},F5=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,v,x,y,z,E,I,K,N,aa,J,oa,ia,za,jb,Gb;
return g.B(function(Ra){switch(Ra.j){case 1:return e=g.MK(a,"ytMainVideoEntity"),f=g.MK(a,"ytMainChannelEntity"),k=g.MK(a,"transfer"),g.A(Ra,l5(b,{mode:"readonly",Kc:!0},function(rc){return g.Rs.all([d5(rc,e,"ytMainVideoEntity"),d5(rc,f,"ytMainChannelEntity"),d5(rc,k,"transfer"),e5(rc,"ytMainChannelEntity"),e5(rc,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=Ra.u;m=g.r(l);n=m.next().value;p=m.next().value;q=m.next().value;t=m.next().value;v=m.next().value;x=n;y=p;z=q;E=t;I=v;if(!x&&!y){Ra.Za(3);break}K=x?D5(x.thumbnail):[];if(!y){N=[];Ra.Za(4);break}return g.A(Ra,NYa(y,E),5);case 5:N=Ra.u;case 4:return aa=N,g.A(Ra,LYa(K.concat(aa)),3);case 3:J=[];oa=g.MK(a,"ytMainDownloadedVideoEntity");ia=g.r(I);for(za=ia.next();!za.done;za=ia.next())jb=za.value,Gb=g.LK(jb.key).entityId,Gb!==a||OYa(c,jb.actionProto)||J.push(jb.key);return g.A(Ra,l5(b,{mode:"readwrite",
Kc:!0},function(rc){var Xc=J.map(function(Hb){return i5(rc,Hb)});
Xc.push(i5(rc,oa,{oL:!0}));return g.Rs.all(Xc)}),7);
case 7:PYa(z),E5(d,{entityKey:oa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.ua(Ra)}})},RYa=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,l5(a,{mode:"readwrite",Kc:!0},function(p){var q=e5(p,"transfer"),t=e5(p,"offlineOrchestrationActionWrapperEntity");return g.Rs.all([q,t]).then(function(v){v=g.r(v);var x=v.next().value,y=v.next().value;v=QYa.map(function(K){return vYa(p,K)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var E="ytMainDownloadedVideoEntity"===g.LK(z.actionProto.entityKey).entityType,I="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;OYa(b,z.actionProto)||E&&(!E||I)||v.push(i5(p,z.key,{oL:!0}))}return g.Rs.all(v).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())k=f.value,PYa(k),l=g.LK(k.key).entityId,m=g.MK(l,"ytMainDownloadedVideoEntity"),E5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,KYa(),0)})},OYa=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},PYa=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.LK(a.key).entityId;
s5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,ji:a})}},D5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},NYa=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){c=D5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.r(D5(f.avatar)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},G5=function(a){this.j=a},SYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Za(4);break}f=e.value;k=c;l=k.set;m=f;return g.A(n,a.B(f),5);case 5:l.call(k,m,n.u);e=d.next();n.Za(2);break;case 4:return n.return(c)}})},H5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},I5=function(a,b,c){g.Ov(new g.Fs("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.Ov(b)},J5=function(a,b,c){this.j=a;
this.Y=b;this.u=c},VYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.va(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,TYa(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,FQ:q}),4);case 4:return(k=n.u)?g.A(n,UYa(a,k,b),5):n.return(K5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(K5(b,!0,k.orchestrationActions));case 2:return l=g.xa(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Ks&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),I5("PDE handleAdd error"),n.return(K5(b,!1,void 0,m))}})},WYa=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,v,x,y,z;
return g.B(function(E){switch(E.j){case 1:return c=b.entityKey,g.A(E,l5(a.j,{mode:"readonly",Kc:!0},function(I){var K=d5(I,c,"playbackData"),N=d5(I,g.MK(g.LK(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");I=d5(I,g.MK(g.LK(b.entityKey).entityId,"transfer"),"transfer");return g.Rs.all([K,N,I])}),2);
case 2:d=E.u;e=g.r(d);f=e.next().value;k=e.next().value;l=e.next().value;m=f;n=k;p=l;if(!m||!n)return E.return(K5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(v=p)?0:v.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.va(E,3);return g.A(E,TYa(a,c,{refreshData:q,FQ:t}),5);case 5:return(x=E.u)?g.A(E,UYa(a,x,b),6):E.return(K5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return E.return(K5(b,
!0,x.orchestrationActions));case 3:return y=g.xa(E),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.Ks&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),E.return(K5(b,!1,void 0,z))}})},TYa=function(a,b,c){var d,e,f;
return g.B(function(k){d=g.XJ();var l=a.Y,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.FQ,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.tK(l),signatureTimestamp:19072,videos:[q]};f=g.GJ(XYa);return k.return(g.TH(d,e,f))})},UYa=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Za(2);d=g.LK(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,F5(d,a.j,c,a.u),2)}return g.A(e,FYa(b.frameworkUpdates.entityBatchUpdate),0)})},K5=function(a,
b,c,d){return new H5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",A5(a),c,d)},L5=function(){G5.apply(this,arguments)},ZYa=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=A5(b),g.A(e,o5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(e,3);return g.A(e,YYa(a,b),5);case 5:g.wa(e,4);break;case 3:return g.xa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},$Ya=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=A5(b),g.A(e,o5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(e,3);return g.A(e,YYa(a,b,!0),5);case 5:g.wa(e,4);break;case 3:return g.xa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},YYa=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.pv(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(k=e)?void 0:k.preferredAudioTrack,transferRetryCount:0,isRefresh:c},m=g.LK(l.key).entityId,g.A(n,l5(a.j,{mode:"readwrite",Kc:!0},function(p){var q=[];c&&q.push(i5(p,
g.MK(m,"offlineVideoStreams")));q.push(g5(p,l,"transfer"));return g.Rs.all(q)}),2);
s5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,ji:l});g.ua(n)})},aZa=function(a,b,c){return new g.UD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},bZa=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},M5=function(a,b,c,d,e,f,k,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=k;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},N5=function(a){return{key:g.MK(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},cZa=function(){this.j=new Map},dZa=function(){O5||(O5=new cZa);
return O5},eZa=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},fZa=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.pv(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.As("flowEvent",a,void 0)},gZa=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.LK(a.action.entityKey);a={entityType:d.pU,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},P5=function(a,b){var c={offlineOrchestrationContext:gZa(a)};
b=eZa(b,c);fZa(dZa(),b,a.rootActionId)},Q5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:gZa(a,b,c)};b=eZa(3,b);fZa(dZa(),b,a.rootActionId)},hZa=function(){this.actions=[]},iZa=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,P5(c,1),a.actions.push(c);a.actions.sort(a.j)},jZa=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},R5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.ma=b;this.X=c;this.D=d;this.j=new hZa;this.N=new g.Rt;this.C=new g.L(function(){e.retry()});
this.J=NaN;g.H(this,this.C);this.K=m5(this.u,this.Z.bind(this))},lZa=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new R5(a,b,c,d),g.A(f,kZa(e),2);e.B?Promise.resolve():S5(e);return f.return(e)})},S5=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,v,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();mZa(a.X,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.ma[b.entityType]){z.Za(2);break}a.B=void 0;return g.A(z,S5(a),3);case 3:return z.return();case 2:f=g.r(c);for(k=f.next();!k.done;k=f.next())l=k.value,P5(l,2);g.va(z,
4,5);return g.A(z,SYa(e,c.map(function(E){return E.action})),7);
case 7:m=z.u,n=g.r(c),k=n.next();case 8:if(k.done){z.Za(5);break}p=k.value;q=m.get(p.action);return g.A(z,nZa(a,p,q),9);case 9:k=n.next();z.Za(8);break;case 5:g.ya(z);a.B=void 0;g.Aa(z,6);break;case 4:return t=g.xa(z),I5("Orchestration error",t),g.va(z,12),g.A(z,oZa(a,c),14);case 14:g.wa(z,5);break;case 12:v=g.xa(z);I5("Orchestration retry error",v);x=g.r(c);for(k=x.next();!k.done;k=x.next())y=k.value,3>y.retryScheduleIndex&&iZa(a.j,[y]);z.Za(5);break;case 6:return g.A(z,S5(a),0)}})},nZa=function(a,
b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){k=void 0;try{k=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return Q5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},E5(a.D,m),I5("Orchestration subactions creation error",p),n.return()}Q5(b,c,k);return g.A(n,l5(a.u,{mode:"readwrite",Kc:!0},function(p){var q=[];if(k){var t=k.map(function(v){return N5(v)});
q.push(h5(p,t,"offlineOrchestrationActionWrapperEntity"))}t=N5(b);q.push(i5(p,t.key));return g.Rs.all(q)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Za(0);
Q5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,oZa(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};E5(a.D,f);I5("Orchestration result is not retryable, deleting action");return g.A(n,BYa(a.u,N5(b).key),0)}P5(b,4);g.ua(n)})},T5=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,v;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(k=f.next();!k.done;k=f.next())l=k.value,m=Number(l.enqueueTimeSec),n=pZa(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.J)&&(a.J=d,a.C.start(e));a.N.Ne()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!qZa.includes(y)}),v=c.length<t,!a.C.isActive()&&v&&a.C.start(1));
0<c.length&&rZa(a,c);return g.A(x,a.B?Promise.resolve():S5(a),0)})},tZa=function(a){var b,c,d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,sZa(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,k=g.LK(f.key),l=k.entityId,jZa(a.j,l)||c.push(f);return g.A(m,T5(a,c),0)})},pZa=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},oZa=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var k=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(k=l.actionMetadata)?void 0:k.retryScheduleIntervalsInSeconds)||[1,2,4];k=1;e.retryScheduleIndex<m.length&&(k=m[e.retryScheduleIndex]);e.j=1E3*k+Date.now();e.retryScheduleIndex++}return g.A(f,uZa(a,b),0)})},kZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,p5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,T5(a,b),0)})},rZa=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.LK(c.key),e=g.LK(c.actionProto.entityKey);c=new M5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&iZa(a.j,[c])})},sZa=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,p5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(GYa))})},uZa=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return N5(c)});
return AYa(a.u,b)},vZa=function(){this.j=void 0},xZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){c=b.videoId;d=b.V();e=!0;if(b.captionTracks.length)f=WXa(b),a.j=new g.vL(d,b,f);else if(b.Hb)k=g.hxa(b),a.j=new g.xL(d,b.Hb,c,k,b.wj),e=b.wj;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.Nt(function(){return g.B(function(p){if(1==p.j)return g.A(p,wZa(a,c,e),2);m();g.ua(p)})})}))})},wZa=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,k,l,m,n,p,q,t,v,x,y,z;return g.B(function(E){switch(E.j){case 1:if(!a.j)return E.return();d=[];e=g.sL(a.j.u,c);f=[];k={};l=g.r(e.entries());for(m=l.next();!m.done;k={EC:k.EC},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,k.EC=q,v=t,x=a.j.rq(v,"json3"),y=g.Gr(x,{withCredentials:!0,format:"RAW"},3,500).then(function(I){return function(K){K={metadata:g.FD(e[I.EC]),trackData:K.xhr.responseText};f.push(K)}}(k)).Eh(function(I){I5("Caption fetch error",I)}),d.push(y);
return g.A(E,XXa(d),2);case 2:return g.va(E,3),g.A(E,aYa(b,f),5);case 5:g.wa(E,0);break;case 3:z=g.xa(E),I5("Caption DB transaction error",z),g.ua(E)}})},yZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,bYa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},zZa=function(a,b){this.api=a;
this.j=b;this.logger=new g.oQ("woffle");this.u=!1;g.vD=this.api.V().S("html5_user_partitioned_ls")},AZa=function(a){return g.B(function(b){return b.return(cYa(a))})},BZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.Tva(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},U5=function(a,b){var c=g.yD(b);
if(1===c||0===c)return Promise.resolve();(c=CZa(a,b))&&c.stopVideo();a.B=0;return AZa(b)},V5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.yD(e)&&((b=CZa(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.zD(e,2),a.B=2,c?DZa(a.j):d&&EZa(a.j))},CZa=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},FZa=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},W5=function(a){g.G.call(this);
this.j=a;this.u=m5(this.j,this.B.bind(this))},GZa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.MK(p,"transfer")});
return g.A(n,p5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(GYa).map(function(p){return g.LK(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);k=g.r(f);l=k.next();case 3:if(l.done){n.Za(5);break}m=l.value;return g.A(n,AZa(m),4);case 4:l=k.next();n.Za(3);break;case 5:return n.return(f)}})},IZa=function(a,b,c,d,e,f){var k,l,m;
return g.B(function(n){k="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(k="STREAM_TYPE_AUDIO_AND_VIDEO",I5("unexpected stream type")):c.video&&!c.audio?k="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(k="STREAM_TYPE_AUDIO");l=g.MK(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:k,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===k?Number(c.Zb()):void 0};return g.A(n,l5(a,{mode:"readwrite",Kc:!0},
function(p){var q=d5(p,l,"offlineVideoStreams"),t=d5(p,g.MK(b,"transfer"),"transfer");return g.Rs.all([q,t]).then(function(v){var x=g.r(v);v=x.next().value;x=x.next().value;if(!x)return i5(p,l).then(function(){});
v=[g5(p,HZa(v,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),v.push(g5(p,x,"transfer")));return g.Rs.all(v)})}),0)})},JZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.MK(b,"offlineVideoStreams"),g.A(l,o5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())k=f.value,k.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",k.numTotalBytes!==k.numBytesDownloaded&&(k.numBytesDownloaded=k.numTotalBytes);return g.A(l,n5(a,d,"offlineVideoStreams"),0)})},HZa=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var k=JSON.parse(e[f].formatStreamBytes);if(k.itag+";"+k.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},X5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.api=b;this.ya=c;this.xa=d;this.D=new g.Rt;this.C=new g.L(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.Ne()&&(3>(e.j.transferRetryCount||0)?V5(e.J,e.B,!1,!1):U5(e.J,e.B.videoDetails.videoId),e.Qq("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.X=0;this.va=new g.dA(this);this.K=m5(this.u,this.QS.bind(this));this.J=new zZa(b,this);this.Ia=new vZa;this.N=new W5(this.u);this.ma=this.D.Pa("publicytnetworkstatus-online",this.by.bind(this));this.Z=this.D.Pa("publicytnetworkstatus-offline",this.jZ.bind(this));g.H(this,this.va);this.va.T(b,"offlinetransferpause",this.kZ);this.Ea=g.YA(this.api.V().experiments,"web_player_transfer_timeout_threshold_ms")},KZa=function(a){g.B(function(b){if(1==b.j)b=g.A(b,$Xa(),2);
else{var c=a.N;var d=g.xD();d=Object.keys(d);c=GZa(c,d);b=g.A(b,c,0)}return b})},Z5=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,LZa(a),2)}return 4!=d.j?(c=d.u,MZa(a.ya,!c),c&&a.D.Ne()?b?g.A(d,new Promise(function(e){g.tr(e,1E3)}),4):d.Za(4):(!c&&a.j&&Y5(a),d.Za(0))):g.A(d,NZa(a,c),0)})},OZa=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,U5(a.J,a.B.videoDetails.videoId),3):b.Za(0);
Y5(a);g.ua(b)})},PZa=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.va(f,2),(c=!!b.captionTracks.length||!!b.Hb)?g.A(f,yZa(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,xZa(a.Ia,b),5);case 5:g.wa(f,0);break;case 2:e=g.xa(f),I5("Caption downloading error",e,b.cotn),g.ua(f)}})},NZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.LK(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState?s5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,ji:a.j}):"TRANSFER_STATE_TRANSFER_IN_QUEUE"!==a.j.transferState||a.j.transferRetryCount||s5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!0},{videoId:c.entityId,ji:a.j}),g.A(l,$5(a),2);case 2:return d=null,
g.va(l,3),g.A(l,QZa(a,b),5);case 5:d=l.u;a.B=d;g.wa(l,4);break;case 3:return e=g.xa(l),I5("error getting player response",e,b.cotn),g.A(l,a.Qq("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=aZa(a.api.V(),b.cotn,d),g.A(l,PZa(a,f),7);case 7:return k=f,g.A(l,BZa(f.videoId),8);case 8:k.Ul=l.u;var m=a.J,n=b.maximumDownloadQuality;f.getPlayerResponse();g.zD(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.Nn(9,f);p={};g.fv(m.player,(p.localmediachange=
m.qB,p.signatureexpired=m.QG,p.statechange=m.ZW,p),m);n=FZa(n);m.S("hoffle_lmqf_killswitch")||(n=g.Gx(n,n,!0,"m"),g.xMa(m.player,n,!1));g.FP(m.player,!1);a6(a);g.ua(l)}})},LZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,p5(a.u,"transfer"),2);b=d.u;c=b.filter(RZa).sort(SZa);return 0===c.length?d.return():d.return(c[0])})},$5=function(a){return g.B(function(b){a6(a);
return g.A(b,b6(a,"TRANSFER_STATE_TRANSFERRING"),0)})},DZa=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,b6(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.LK(a.j.key);HYa({videoId:b.entityId,ji:a.j});Y5(a);Z5(a);g.ua(c)})},EZa=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,b6(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
Y5(a);g.ua(b)})},TZa=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Za(2);break}b=aZa(a.api.V(),a.j.cotn,a.B);return g.A(e,PZa(a,b),2);case 2:return g.A(e,b6(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.LK(a.j.key),d=c.entityId,g.A(e,JZa(a.u,d),5);case 5:s5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,ji:a.j}),Y5(a),Z5(a),g.ua(e)}})},UZa=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Za(2);break}return g.A(e,$5(a),2);case 2:d=Date.now();if(!(1E3<d-a.X)){e.Za(4);break}a.X=d;return g.A(e,IZa(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:var f=Math.floor(c.bytesDownloaded/1024).toFixed();s5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",alreadyDownloadedKbytes:f,totalFetchedKbytes:f,totalContentKbytes:Math.floor(c.j/1024).toFixed()},
{videoId:b,ji:a.j});case 4:a6(a),g.ua(e)}})},VZa=function(a){var b=3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},WZa=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,b6(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);E5(a.xa,{entityKey:a.j.key,failureReason:c});d=g.LK(a.j.key).entityId;var f={videoId:d,ji:a.j},k=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};k&&(l.transferFailureReason=k,l.failureReason=IYa(k));s5(l,f);g.ua(e)})},b6=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.va(f,2),g.A(f,XZa(a,function(k){return c?e5(k,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return h5(k,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.Rs.resolve(void 0)}),4);
if(2!=f.j)return g.wa(f,0);e=g.xa(f);return e instanceof g.Ks&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.Qq("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Za(0)})},XZa=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,l5(a.u,{mode:"readwrite",Kc:!0},function(e){var f=[g5(e,c,"transfer")];b&&f.push(b(e));return g.Rs.all(f)}),0)})},Y5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},QZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.LK(b.key),d=c.entityId,e=g.MK(d,"playbackData"),g.A(l,o5(a.u,e,"playbackData"),2);f=l.u;if(null==(k=f)?0:k.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},a6=function(a){a.C.start(a.Ea||18E5)},RZa=function(a){return void 0!==c6[a.transferState]},SZa=function(a,b){var c=c6[a.transferState],d=c6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},YZa=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,v,x,y,z,E;
return g.B(function(I){if(1==I.j)return g.A(I,l5(a,{mode:"readonly",Kc:!0},function(K){return e5(K,"playbackData").then(function(N){var aa=N.map(function(oa){return oa.transfer}).filter(function(oa){return!!oa}),J=N.map(function(oa){return oa.offlineVideoPolicy}).filter(function(oa){return!!oa});
aa=e5(K,"transfer",aa);J=e5(K,"offlineVideoPolicy",J);return g.Rs.all([aa,J]).then(function(oa){var ia=g.r(oa);oa=ia.next().value;ia=ia.next().value;return[N,oa,ia]})})}),2);
b=I.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;k=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(v=t.value)&&(n[v.key]=v);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);E=k.map(function(K){var N=n[K.transfer],aa=p[K.offlineVideoPolicy];K=g.LK(aa.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===aa.action){var J="OFFLINE_VIDEO_STATE_DISABLED";aa.expirationTimestamp&&Number(aa.expirationTimestamp)<Date.now()/1E3&&(J="OFFLINE_VIDEO_STATE_EXPIRED");
aa=J}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===aa.action)aa="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==N?void 0:N.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":J="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":J="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":J="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":J="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":J=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":J="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:J="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===J)switch(null==N?void 0:N.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":J="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":J="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":J="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}aa=J}K={id:K,videoState:aa};if(null==N?0:N.cotn)K.cotn=N.cotn;if(null==N?0:N.maximumDownloadQuality)K.selectedVideoQuality=null==N?void 0:N.maximumDownloadQuality;return K});
return I.return({offlineVideos:E})})},ZZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,YZa(a),2);b=c.u;g.As("offlineStateSnapshot",b);g.ua(c)})},d6=function(a){g.G.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.Gs()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.Gs()),this.u.onmessage=this.C.bind(this))},E5=function(a,b){a.api.Oa("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},$Za=function(){this.locks=navigator.locks},a_a=function(){try{var a=g.Ka("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new $Za,g.Ja("ytglobal.locks_",a,void 0),a}catch(d){}},c_a=function(a,b,c,d){var e=this;
this.N=a;this.X=b;this.visibility=c;this.S=d;this.C=this.J=this.D=this.u=this.j=!1;this.K=new g.L(function(){b_a(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.Oe()})},d_a=function(a){if(!a.u&&!a.j){var b=a_a();
if(b){a.u=!0;var c=g.Gs("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,k;return g.B(function(l){switch(l.j){case 1:return g.va(l,2),a.B=new g.Nj,a.j=!0,a.u=!1,g.A(l,a.N(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.wa(l,0);break;case 2:d=g.xa(l),(null==(f=(e=a).S)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||b_a(a),d instanceof Error&&(k=d,k.args=[{name:"WoLockManagerError",yB:d.name}],g.S(k)),g.ua(l)}})})}}},e_a=function(a){a.j&&(a.C=
!0,e6(a))},mZa=function(a,b){a.j&&(a.D=b,e6(a))},MZa=function(a,b){a.j&&(a.J=b,e6(a))},e6=function(a){a.J&&a.D&&a.C&&a.visibility.isBackground()?g.qp(a.K,6E4):a.K.stop()},b_a=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.X()},f6=function(a,b){var c=this;
this.Y=a;this.api=b;this.N=new g.Rt;this.u=new c_a(function(){return f_a(c)},function(){g_a(c)},this.api.Co(),this.api.S.bind(this.api));
this.B=new d6(this.api);this.C=new g.Nj;d_a(this.u)},f_a=function(a){return g.B(function(b){a.api.Oa("onOrchestrationBecameLeader");
a.j&&a.D||h_a(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},h_a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,r5(),2);if(3!=e.j){b=e.u;if(!b)return I5("PES is undefined"),e.return();a.j=new X5(b,a.api,a.u,a.B);c=a.hF(b);d=a;return g.A(e,lZa(b,c,a.u,a.B),3)}d.D=e.u;return g.A(e,i_a(a),0)})},i_a=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return I5("transferManager is undefined"),c.return();if(a.j.j){c.Za(2);break}return g.A(c,Z5(a.j),2);case 2:return g.A(c,a.Wx(),4);case 4:return a.J=g.yr(function(){a.Wx()},9E5),g.Qr(g.Sr(),function(){a.j&&KZa(a.j)}),g.A(c,r5(),5);
case 5:return b=c.u,g.A(c,ZZa(b),6);case 6:e_a(a.u),g.ua(c)}})},g_a=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(g.Ar(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.Oa("onOrchestrationLostLeader");a.C=new g.Nj;g.ua(d)})},j_a=function(){var a,b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return g.A(k,r5(),2);case 2:a=k.u;if(!a)return k.return([]);b=Date.now()/1E3;return g.A(k,p5(a,"offlineVideoPolicy"),3);case 3:c=k.u,d=g.r(c),e=d.next();case 4:if(e.done){k.Za(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){k.Za(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(k,n5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();k.Za(4);break;case 6:return k.return(c.map(function(l){return l.key}))}})},g6=
function(a,b,c,d,e){var f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,r5(),2);f=m.u;if(!f)return m.return([]);k=b.map(function(n){var p=g.MK(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},bZa(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new M5(c,n,p);return N5(n)});
l=AYa(f,k);d_a(a.u);return m.return(l)})},l_a=function(a){var b,c,d,e;
return g.B(function(f){if(1==f.j)return b=g.XJ(),c=dYa(a),d=g.GJ(k_a),g.A(f,g.TH(b,c,d),2);e=f.u;if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return f.return(e.videos.map(function(k){return k.offlineVideoData}))})},h6=function(a,b,c){this.j=a;
this.Y=b;this.u=c},o_a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=A5(b),d=g.LK(b.entityKey),e=d.entityId,g.va(m,2),g.A(m,m_a(a,e),4);case 4:g.wa(m,3);break;case 2:return f=g.xa(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Ks&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=n_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},p_a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return c=A5(b),d=g.LK(b.entityKey),e=d.entityId,g.A(n,o5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(n,3);return g.A(n,m_a(a,e,f.addedTimestampMillis),5);case 5:k=n_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.wa(n,4);break;case 3:return l=g.xa(n),l instanceof Error&&"No data"===l.message?g.A(n,F5(e,a.j,b,a.u),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.Ks&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,k?[k]:void 0))}})},q_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=A5(b),g.va(e,2),d=g.LK(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,RYa(a.j,b,a.u),5):g.A(e,F5(d,a.j,b,a.u),5);case 5:g.wa(e,3);break;case 2:return g.xa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},m_a=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,l_a([b]),2);case 2:return d=n.u,e=d[0],g.A(n,r_a(a,e,c),3);case 3:f=n.u;k=f.videoEntity;l=f.channelEntity;g.va(n,4);var p=D5(k.thumbnail),q=D5(l.avatar);return g.A(n,MYa(p.concat(q)),6);case 6:g.wa(n,0);break;case 4:m=g.xa(n);if(!a.Y.S("woffle_disable_thumbnails"))throw m;g.ua(n)}})},r_a=function(a,b,c){var d,e,f,k,l;
return g.B(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.MK(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={id:g.MK(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.MK(b.videoId,"ytMainDownloadedVideoEntity"),video:k.id,playbackData:g.MK(b.videoId,"playbackData"),offlineVideoPolicy:g.MK(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return g.A(m,l5(a.j,{mode:"readwrite",Kc:!0},function(n){var p=g5(n,f,"ytMainChannelEntity"),q=g5(n,k,"ytMainVideoEntity");n=g5(n,l,"ytMainDownloadedVideoEntity");
return g.Rs.all([p,q,n])}),2)}return m.return({videoEntity:k,
channelEntity:f,Tga:l})})},n_a=function(a,b,c){b=g.MK(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:s_a});return{actionType:a,entityKey:b,actionMetadata:c}},i6=function(){f6.apply(this,arguments);
this.K="ytMainDownloadedVideoEntity"},j6=function(){g.rL.apply(this,arguments)};
g.w(s4,r4);g.w(t4,s4);t4.prototype.fd=function(){return[]};
g.w(u4,s4);u4.prototype.fd=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.u(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.u(new Set(a)))};
g.w(v4,s4);v4.prototype.fd=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.u(new Set(a)))};
g.w(w4,r4);w4.prototype.fd=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.u(new Set(a)))};
g.w(x4,s4);x4.prototype.fd=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.u((new w4(c.value)).fd()));return[].concat(g.u(new Set(a)))};
g.w(y4,s4);y4.prototype.fd=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.u(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.u(new Set(a)))};
g.w(z4,s4);z4.prototype.fd=function(){return[]};
g.w(A4,s4);A4.prototype.fd=function(){return[]};
g.w(B4,s4);B4.prototype.fd=function(){return[]};
g.w(C4,s4);C4.prototype.fd=function(){return[]};
g.w(D4,s4);D4.prototype.fd=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));return[].concat(g.u(new Set(a)))};
g.w(E4,s4);E4.prototype.fd=function(){return[]};
g.w(F4,s4);F4.prototype.fd=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.u(this.j.fakeChildren));return[].concat(g.u(new Set(a)))};
g.w(G4,s4);G4.prototype.fd=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(H4,s4);H4.prototype.fd=function(){return[]};
g.w(I4,r4);I4.prototype.fd=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.u(new Set(a)))};
g.w(J4,s4);J4.prototype.fd=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.u((new I4(this.j.userState)).fd()));return[].concat(g.u(new Set(a)))};
g.w(K4,s4);K4.prototype.fd=function(){return[]};
g.w(L4,s4);L4.prototype.fd=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.u(new Set(a)))};
g.w(M4,s4);M4.prototype.fd=function(){return[]};
g.w(N4,s4);N4.prototype.fd=function(){return[]};
g.w(O4,s4);O4.prototype.fd=function(){return[]};
g.w(P4,s4);P4.prototype.fd=function(){return[]};
g.w(Q4,s4);Q4.prototype.fd=function(){return[]};
g.w(R4,s4);R4.prototype.fd=function(){return[]};
g.w(S4,s4);S4.prototype.fd=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.u(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(T4,s4);T4.prototype.fd=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.u(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.u(this.j.captionTrack));return[].concat(g.u(new Set(a)))};
g.w(U4,s4);U4.prototype.fd=function(){return[]};
g.w(V4,s4);V4.prototype.fd=function(){return[]};
g.w(W4,s4);W4.prototype.fd=function(){return[]};
var k_a=["offline"],XYa=["offline/get_playback_data_entity"],t_a={u1:"captionTrack",U8:"ytMainChannelEntity",V8:"ytMainDownloadedVideoEntity",W8:"ytMainVideoEntity",Maa:"offlineOrchestrationActionWrapperEntity",Waa:"offlineVideoPolicy",Xaa:"offlineVideoStreams",Lba:"playbackData",pea:"transfer",Gca:"orchestrationWebSamplingEntity"};g.w(Y4,g.Fs);g.w($4,iYa);$4.prototype.B=function(a,b){b=Z4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
$4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw eYa(1);var c=new TextDecoder;b=Z4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
g.w(a5,iYa);a5.prototype.B=function(a){return a};
a5.prototype.u=function(a){if(a instanceof Uint8Array)throw eYa(0);return a};
var mYa={captionTrack:O4,channelHandle:t4,commerceCartListEntity:V4,downloadQualityPickerEntity:C4,fakeChannel:u4,fakePlaylist:v4,fakePlaylistEntryCollection:x4,fakeVideo:y4,fakeVideoDescription:z4,iconBadgeEntity:W4,liveChatPollStateEntity:B4,logoEntity:A4,mainPlaylistEntity:H4,mainVideoDownloadStateEntity:D4,mainVideoEntity:J4,markersVisibilityOverrideEntity:M4,offlineOrchestrationActionWrapperEntity:P4,offlineVideoPolicy:Q4,offlineVideoStreams:R4,offlineabilityEntity:E4,orchestrationWebSamplingEntity:F4,
pinnedProductEntity:N4,playbackData:S4,transfer:T4,videoPlaybackPositionEntity:U4,ytMainChannelEntity:K4,ytMainDownloadedVideoEntity:G4,ytMainVideoEntity:L4},c5;g.w(k5,g.G);k5.prototype.B=function(a){zYa(this,a.data)};
k5.prototype.ra=function(){this.channel.close()};
var q5;var x5=g.C.caches,w5,y5;t5.prototype.open=function(a){return x5.open(v5(a))};
t5.prototype.has=function(a){return x5.has(v5(a))};
t5.prototype.delete=function(a){return x5.delete(v5(a))};
t5.prototype.match=function(a,b){var c=this,d,e,f,k,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Za(5);break}k=f.value;return g.A(n,c.open(k),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Za(3);break;case 5:return n.return()}})};
g.w(u5,t5);u5.prototype.keys=function(){var a,b,c,d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.Gs("CacheStorage keys"),g.A(n,x5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");k=-1===p?{yB:f}:{yB:f.substring(0,p),datasyncId:f.substring(p+1)};l=k.yB;m=k.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(t_a).map(function(a){return t_a[a]});
var QYa="captionTrack ytMainChannelEntity ytMainDownloadedVideoEntity ytMainVideoEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(J5,G5);J5.prototype.B=function(a){return B5(a)?VYa(this,a):C5(a)?WYa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(L5,G5);L5.prototype.B=function(a){return B5(a)?ZYa(this,a):C5(a)?$Ya(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
L5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=A5(a),g.A(f,o5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.va(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,n5(b.j,d,"transfer"),5);case 5:e=g.LK(d.key).entityId;s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,ji:d});g.wa(f,4);break;case 3:return g.xa(f),f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var qZa=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var O5;hZa.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(R5,g.G);R5.prototype.ra=function(){this.K&&this.K();g.G.prototype.ra.call(this)};
R5.prototype.createAction=function(a,b){var c=g.LK(a.entityKey).entityType,d=g.pv(16);return new M5(c,d,a,b.actionId,b.rootActionId)};
R5.prototype.Z=function(a){var b=this,c,d,e,f,k,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.LK(l),n=m.entityId,jZa(b.j,n)||e.push(l);return g.A(q,sZa(b,e),2)}p=q.u;return g.A(q,T5(b,p),0)})};
R5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,tZa(a),0)})};g.h=zZa.prototype;g.h.ZW=function(a){var b=this,c,d,e;return g.B(function(f){if(!g.V(a.state,128))return f.Za(0);var k=null==(c=a.state.getData())?void 0:c.errorCode,l=null==(d=a.state.getData())?void 0:d.tH;e="net.retryexhausted"===k&&(null==l?0:l.includes("net.connect"))?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==k?0:k.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(f,b.Qq(b.player.getVideoData().videoId,e),0)})};
g.h.Qq=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(V5(c,a,!1,!0),d.Za(0)):g.A(d,U5(c,a),3)}g.zD(a,4);return g.A(d,c.j.Qq(b),0)})};
g.h.qB=function(a){2===a.status?(a.status!==this.B&&($5(this.j),g.zD(a.videoId,2)),a.Px&&UZa(this.j,a.videoId,a.Px)):4===a.status?(U5(this,a.videoId),this.Qq(a.videoId,a.EA?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&TZa(this.j);this.B=a.status;this.api.Oa("localmediachange",{videoId:a.videoId,status:a.status})};
g.h.QG=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,U5(a,b),2)}return g.A(c,a.j.QG(),0)})};
g.h.S=function(a){return this.api.V().S(a)};g.w(W5,g.G);W5.prototype.ra=function(){this.u&&this.u();g.G.prototype.ra.call(this)};
W5.prototype.B=function(a){var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.LK(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,GZa(b,e),0)})};g.w(X5,g.G);g.h=X5.prototype;g.h.ra=function(){this.K&&this.K();this.N.dispose();this.C.dispose();this.ma&&g.mg(this.D.B,this.ma);this.Z&&g.mg(this.D.B,this.Z);g.G.prototype.ra.call(this)};
g.h.kZ=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.MK(a,"transfer"),b.j&&c===b.j.key?(V5(b.J,b.B,!0),b.C.stop(),e.Za(0)):g.A(e,l5(b.u,{mode:"readwrite",Kc:!0},function(f){return d5(f,c,"transfer").then(function(k){if(k&&"TRANSFER_STATE_COMPLETE"!==k.transferState&&"TRANSFER_STATE_FAILED"!==k.transferState)return k.transferState="TRANSFER_STATE_PAUSED_BY_USER",g5(f,k,"transfer").then(function(){return k})})}),3);
(d=e.u)&&HYa({videoId:a,ji:d});g.ua(e)})};
g.h.jZ=function(){this.j&&this.B&&V5(this.J,this.B,!1);this.C.stop()};
g.h.by=function(){this.j?NZa(this,this.j):Z5(this)};
g.h.QS=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Za(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Za(3);break}c=b;return g.A(d,o5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Za(3);break}return g.A(d,OZa(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,Z5(b),0)}})};
g.h.Qq=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var k=!1;break a;default:k=!0}return k&&VZa(c)?g.A(f,b6(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,WZa(c,a),3)}3!=f.j&&(d=g.LK(c.j.key).entityId,s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,ji:c.j}));Y5(c);e=Z5(c,!0);b&&b(e);g.ua(f)})};
g.h.QG=function(a){var b=this,c,d,e,f,k,l;return g.B(function(m){if(1==m.j)return VZa(b)?g.A(m,b6(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,WZa(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.LK(b.j.key).entityId,s5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,ji:b.j}),d=bZa(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.MK(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},k=N5(new M5("playbackData",c,f)),g.A(m,n5(b.u,k,"offlineOrchestrationActionWrapperEntity"),3);Y5(b);l=Z5(b,!0);a&&a(l);g.ua(m)})};
var k6={},c6=(k6.TRANSFER_STATE_TRANSFERRING=1,k6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,k6);g.w(d6,g.G);d6.prototype.B=function(a){this.api.Oa("onOfflineOperationFailure",a.data)};
d6.prototype.C=function(a){this.api.ea("offlinetransferpause",a.data)};
d6.prototype.ra=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};$Za.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};c_a.prototype.Oe=function(){this.j&&e6(this)};g.h=f6.prototype;g.h.hF=function(a){var b={};return b.playbackData=new J5(a,this.Y,this.B),b.transfer=new L5(a),b};
g.h.isOrchestrationLeader=function(){return this.u.j};
g.h.hH=function(a){var b=this.B;b.api.ea("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.h.by=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,r5(),2);b=d.u;if(!b)return d.return();c=g.MK(a,"transfer");return g.A(d,l5(b,{mode:"readwrite",Kc:!0},function(e){return d5(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",g5(e,f,"transfer").then(function(){s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,ji:f});return g.Rs.resolve(null)})):
g.Rs.resolve(null)})}),0)})};
g.h.Wx=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){if(1==p.j)return b.N.Ne()?g.A(p,r5(),2):p.return(j_a());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,p5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];k=g.r(e);for(l=k.next();!l.done;l=k.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.LK(m.key).entityId,f.push(n));return f.length?p.return(g6(b,f,b.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.h.deleteAll=function(){return g6(this,["!*$_ALL_ENTITIES_!*$"],this.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(h6,G5);h6.prototype.B=function(a){return B5(a)?o_a(this,a):C5(a)?p_a(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&a.entityKey?q_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var s_a=[10];g.w(i6,f6);i6.prototype.hF=function(a){var b=f6.prototype.hF.call(this,a);b.ytMainDownloadedVideoEntity=new h6(a,this.Y,this.B);return b};g.w(j6,g.rL);g.h=j6.prototype;g.h.create=function(){var a=this.player.V();g.WC(a)&&(this.j=new i6(a,this.player))};
g.h.ai=function(){return!1};
g.h.uH=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return(g6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.h.deleteAll=function(){return this.j.deleteAll()};
g.h.Wx=function(a){return this.j.Wx(a)};
g.h.hH=function(a){this.j.hH(a)};
g.h.by=function(a){return this.j.by(a)};
g.h.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.qL("offline",j6);})(_yt_player);
